apiVersion: 1

datasources:
  # Prometheus datasource for metrics
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      timeInterval: 15s
      cacheTimeout: 60
      httpMethod: GET
    editable: true

  # Loki datasource for logs
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    jsonData:
      maxLines: 1000
      derivedFields:
        - name: TraceID
          matcherRegex: 'trace_id=([^\s]+)'
          url: '$${__value.raw}'
          datasourceUid: jaeger
        - name: SpanID
          matcherRegex: 'span_id=([^\s]+)'
          url: '$${__value.raw}'
          datasourceUid: jaeger
    editable: true

  # Jaeger datasource for distributed tracing
  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://jaeger-all-in-one:16686
    uid: jaeger
    jsonData:
      nodeGraph:
        enabled: true
      tracesToLogs:
        datasourceUid: loki
        tags:
          - key: trace_id
            value: trace_id
          - key: span_id
            value: span_id
      logsToTraces:
        datasourceUid: loki
        mappedFields:
          - sourceField: trace_id
            targetField: trace_id
          - sourceField: span_id
            targetField: span_id
    editable: true

  # AlertManager datasource for alert visualization
  - name: AlertManager
    type: alertmanager
    access: proxy
    url: http://alertmanager:9093
    jsonData:
      implementation: prometheus
    editable: true

  # Cloud Datasource
  - name: CloudWatch
    type: cloudwatch
    access: proxy
    jsonData:
      authType: default
      defaultRegion: us-east-1
    editable: false

deleteDatasources:
  - name: CloudWatch
    orgId: 1
